import { CodegenConfig } from '@graphql-codegen/cli'
import dotenv from 'dotenv'
import packages from './package.json'

// Load environment variables from .env file
const isProd = process.argv.some((a) => a === '--prod')
dotenv.config({ path: `./.env.${isProd ? 'production' : 'development'}` })

const config: CodegenConfig = {
  emitLegacyCommonJSImports: false,
  debug: true,
  verbose: true,
  overwrite: true,
  schema: [
    {
      [`https://api-dev.starpx.com/graphql`]: {
        headers: {
          ['Authorization']: 'eyJraWQiOiJ1bVR2d09jQVVGM1NTU1IySXZPY3pMczZDZG94XC9Hd0FRRmtyQVJWUGdjUT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJlNDk4ZTQwOC0yMDYxLTcwMTQtZDA1Zi0yNGQ5ZDMwYmFkYzAiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9NUExNUGJPcm4iLCJjbGllbnRfaWQiOiI3cGs1M2YwMjFwbm44cXJyM2x1dDdtM3FnbSIsIm9yaWdpbl9qdGkiOiJlYmMyNTYzYS1kNDAxLTRjNDYtOTQ0My0wNDkyMDMyZWE3YzUiLCJldmVudF9pZCI6IjRkMTM1NjY1LTdiZmQtNGQ5NS05NDA1LWRiODA4YWM3YTQwZiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE3MjY5MzIzMjAsImV4cCI6MTcyNjkzNTkyMCwiaWF0IjoxNzI2OTMyMzIwLCJqdGkiOiIwN2MzMDY2Ni1iNDA4LTQ0MGUtYjVmYi1lMWM2MDI4NmI2ZjYiLCJ1c2VybmFtZSI6ImU0OThlNDA4LTIwNjEtNzAxNC1kMDVmLTI0ZDlkMzBiYWRjMCJ9.N180dzUly9pfQHfb4rKqIvoxyjLDgKLIB1DW6k-qw4JqKy2VP5STKkeZiJKsv6cGeHYN5qT4_GUJIAnpaeYdlE7ND2H92SsjKonx-f5X9N7I2s0I4vZZXN1wCeT3Pn0cCo476HnGIxwbvXiSgqj9K43HVGW2EUJwHb_y0b9sXrP-_oYI-uiy8t5mlpJlOjedA7w5Vq_531Z26ryCZH6omeRtdetZa9-dd7NZWyKd-EFbAOdd3gGNxqARDCF_2GAUV__WBqZBfY1kdQQa00H3KtDiP9BuV6wIWxiIsywNEGlzyC91fACqSIsNt7Iytafx7I7fadobYqtN1mONBbg4Ew'
        },
      },
    },
  ],
  documents: './src/graphql/*.graphql',
  ignoreNoDocuments: true,
  generates: {
    './src/graphql/generated/graphql.schema.json': {
      plugins: ['urql-introspection'],
    },
    './src/graphql/generated/index.ts': {
      config: {
        addDocBlocks: false,
        pureMagicComment: true, // for tree shaking
        documentMode: 'graphQLTag',
        omitOperationSuffix: true,
        dedupeOperationSuffix: true,
        avoidOptionals: false,
        arrayInputCoercion: false,
        constEnums: true,
        enumsAsConst: true,
        enumsAsTypes: true,
        immutableTypes: true,
        useImplementingTypes: true,
        scalars: {
          AWSJSON: 'string',
          AWSDate: 'string',
          AWSTime: 'string',
          AWSDateTime: 'string',
          AWSTimestamp: 'number',
          AWSEmail: 'string',
          AWSURL: 'string',
          AWSPhone: 'string',
          AWSIPAddress: 'string',
        },
      },
      plugins: [
        {
          add: {
            content: `/* eslint-disable */\n/* Generated by @graphql-codegen/cli@${packages.devDependencies['@graphql-codegen/cli']} */`,
          },
        },
        'typescript',
        'typescript-operations',
        'typescript-vue-urql',
      ],
    },
  }
}

export default config
